baseurl: '/'
permalink: pretty
title: 'K4 Cognitive'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"

footer:
  copyright_text: 'Copyright K4 Cognitive'

seo:
  meta_og_title: "JK4 Cognitive"
  meta_og_type: "website"
  meta_og_url: "https://ecstatic-snyder-bd5e05.netlify.app/"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "K4"
  meta_twitter_card: "summary"
  meta_twitter_site: "@johnke11y"
  meta_twitter_creator: "@johnke11y"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md